import mongoose from "mongoose";

const ogAgentSettingsSchema = new mongoose.Schema(
  {
    key: { type: String, default: "company", unique: true, immutable: true },
    agentEnabled: { type: Boolean, default: true },
    allowReadOnlyDatabaseSearch: { type: Boolean, default: true },
    allowReportGeneration: { type: Boolean, default: true },
    allowEmailSearch: { type: Boolean, default: false },
    allowEmailLeadExtraction: { type: Boolean, default: true },
    maximumMessagesPerExtraction: { type: Number, min: 1, max: 250, default: 50 },
    minimumDefaultConfidence: { type: Number, min: 0, max: 100, default: 70 },
    requireApprovalForLeadImport: { type: Boolean, default: true, validate: { validator: (value) => value === true, message: "Lead import approval is required" } },
    allowCandidateEditing: { type: Boolean, default: true },
    allowBusinessLeadStatusUpdates: { type: Boolean, default: true },
    allowEmailDraftCreation: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Email draft creation is disabled in Phase 2" } },
    allowEmailSending: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Email sending is disabled in Phase 1" } },
    allowMailboxModification: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Mailbox modification is disabled" } },
    allowAutomaticAccountCreation: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Automatic account creation is disabled" } },
    allowAutomaticExistingRecordUpdate: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Automatic existing-record updates are disabled" } },
    allowTelecallingPreparation: { type: Boolean, default: true },
    allowCallingCampaigns: { type: Boolean, default: true },
    allowCallQueueAssignment: { type: Boolean, default: true },
    allowCallOutcomeRecording: { type: Boolean, default: true },
    allowFollowUpManagement: { type: Boolean, default: true },
    allowCallScriptGeneration: { type: Boolean, default: true },
    allowBusinessLeadFieldVerification: { type: Boolean, default: true },
    allowLeadStatusUpdateFromCall: { type: Boolean, default: true },
    allowTelephoneLinks: { type: Boolean, default: true },
    requireManagerApprovalForBulkCampaign: { type: Boolean, default: false },
    maximumLeadsPerCampaign: { type: Number, min: 1, max: 1000, default: 250 },
    maximumActiveQueueItemsPerTelecaller: { type: Number, min: 1, max: 500, default: 100 },
    queueLockMinutes: { type: Number, min: 1, max: 60, default: 15 },
    defaultRetryDays: { type: Number, min: 1, max: 90, default: 3 },
    minimumCallNoteLength: { type: Number, min: 0, max: 500, default: 10 },
    allowAICalling: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "AI calling is disabled in Phase 1" } },
    allowCallRecording: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Call recording is disabled in Phase 3" } },
    allowSMS: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "SMS is disabled in Phase 3" } },
    allowWhatsAppSending: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "WhatsApp sending is disabled in Phase 3" } },
    allowAutomaticEmailSending: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Automatic email sending is disabled in Phase 3" } },
    allowCodeAnalysis: { type: Boolean, default: true },
    allowCodePatchGeneration: { type: Boolean, default: false },
    allowCodeExecution: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Code execution is disabled in Phase 1" } },
    codingAgentEnabled: { type: Boolean, default: true },
    allowRepositoryRead: { type: Boolean, default: true },
    allowRepositorySearch: { type: Boolean, default: true },
    allowCodingAnalysis: { type: Boolean, default: true },
    allowPatchGeneration: { type: Boolean, default: true },
    allowPatchApplication: { type: Boolean, default: true },
    requireApprovalForPatchGeneration: { type: Boolean, default: true, validate: { validator: (value) => value === true, message: "Patch generation approval is mandatory" } },
    requireApprovalForPatchApplication: { type: Boolean, default: true, validate: { validator: (value) => value === true, message: "Patch application approval is mandatory" } },
    requireAdditionalApprovalForHighRiskFiles: { type: Boolean, default: true, validate: { validator: (value) => value === true, message: "Additional high-risk approval is mandatory" } },
    allowSafeCommandExecution: { type: Boolean, default: true },
    requireApprovalForBuild: { type: Boolean, default: true },
    requireApprovalForTests: { type: Boolean, default: true },
    requireApprovalForLint: { type: Boolean, default: true },
    maximumFilesPerTask: { type: Number, min: 1, max: 500, default: 100 },
    maximumBytesPerFile: { type: Number, min: 1024, max: 1000000, default: 200000 },
    maximumTotalReadBytesPerTask: { type: Number, min: 1024, max: 10000000, default: 2000000 },
    maximumPatchBytes: { type: Number, min: 1024, max: 2000000, default: 500000 },
    maximumPatchFiles: { type: Number, min: 1, max: 100, default: 25 },
    maximumCommandOutputBytes: { type: Number, min: 1024, max: 500000, default: 100000 },
    commandTimeoutSeconds: { type: Number, min: 5, max: 600, default: 300 },
    maximumConcurrentCommandRuns: { type: Number, min: 1, max: 4, default: 1 },
    allowLocalBranchCreation: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Local branch creation is disabled in Phase 4" } },
    allowFileCreation: { type: Boolean, default: true },
    allowFileDeletion: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Coding Agent file deletion is locked off" } },
    allowFileRename: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Coding Agent file rename is locked off" } },
    allowLockfileModification: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Coding Agent lockfile modification is locked off" } },
    allowDependencyInstallation: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Dependency installation is locked off" } },
    allowArbitraryTerminal: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Arbitrary terminal is locked off" } },
    allowSecretFileRead: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Secret file access is locked off" } },
    allowGitCommit: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Git commit is locked off" } },
    allowGitPush: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Git push is locked off" } },
    allowGitMerge: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Git merge is locked off" } },
    allowDatabaseWrite: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Database write is locked off" } },
    allowProductionDeployment: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Production deployment is disabled in Phase 1" } },
    requireApprovalForMediumRisk: { type: Boolean, default: true },
    requireApprovalForHighRisk: { type: Boolean, default: true },
    improvementEngineEnabled: { type: Boolean, default: true },
    allowFeedbackCollection: { type: Boolean, default: true },
    allowProposalRevision: { type: Boolean, default: true },
    allowApprovedExampleRetrieval: { type: Boolean, default: true },
    allowOrganizationalGuidanceRetrieval: { type: Boolean, default: true },
    allowImprovementPatternAnalysis: { type: Boolean, default: true },
    allowImprovementProposalGeneration: { type: Boolean, default: true },
    allowEvaluationRuns: { type: Boolean, default: true },
    allowPromptVersionCreation: { type: Boolean, default: true },
    allowRuleVersionCreation: { type: Boolean, default: true },
    requireApprovalForApprovedExampleActivation: { type: Boolean, default: true },
    requireApprovalForGuidanceActivation: { type: Boolean, default: true },
    requireApprovalForPromptActivation: { type: Boolean, default: true },
    requireApprovalForRuleActivation: { type: Boolean, default: true },
    requireApprovalForRollback: { type: Boolean, default: true },
    minimumFeedbackForImprovementProposal: { type: Number, min: 1, max: 100, default: 5 },
    minimumReviewersForOrganizationGuidance: { type: Number, min: 1, max: 20, default: 2 },
    maximumRetrievedExamples: { type: Number, min: 1, max: 20, default: 5 },
    maximumRetrievedGuidance: { type: Number, min: 1, max: 20, default: 5 },
    maximumRevisionAttempts: { type: Number, min: 1, max: 10, default: 3 },
    regressionAlertThreshold: { type: Number, min: 0, max: 100, default: 10 },
    harmfulRecommendationAlertThreshold: { type: Number, min: 0, max: 100, default: 5 },
    humanImpactReviewRequiredForMediumRisk: { type: Boolean, default: true },
    humanImpactReviewRequiredForHighRisk: { type: Boolean, default: true },
    allowAutomaticPromptActivation: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Automatic prompt activation is locked off" } },
    allowAutomaticRuleActivation: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Automatic rule activation is locked off" } },
    allowAutomaticPermissionChange: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Automatic permission changes are locked off" } },
    allowAutomaticToolEnablement: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Automatic tool enablement is locked off" } },
    allowAutomaticSecurityPolicyChange: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Automatic security policy changes are locked off" } },
    allowAutomaticApprovalBypass: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Automatic approval bypass is locked off" } },
    allowAutomaticCodeModification: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Automatic code modification is locked off" } },
    allowAutomaticDeployment: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Automatic deployment is locked off" } },
    allowFeedbackDeletion: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Feedback deletion is locked off" } },
    allowHistoricalRewrite: { type: Boolean, default: false, validate: { validator: (value) => value === false, message: "Historical rewrite is locked off" } },
    researchAgentEnabled: { type: Boolean, default: true }, allowPublicWebsiteResearch: { type: Boolean, default: true }, allowApprovedApiResearch: { type: Boolean, default: true }, allowWebsitePageFetch: { type: Boolean, default: true }, allowApiFetch: { type: Boolean, default: true }, allowPublicBusinessContactExtraction: { type: Boolean, default: true },
    allowPersonalContactExtraction: { type: Boolean, default: false, validate: { validator: (v) => v === false, message: "Personal contact extraction is locked off" } }, allowLeadCandidateCreation: { type: Boolean, default: true }, requireApprovalForContactExtraction: { type: Boolean, default: true }, requireApprovalAbovePageLimit: { type: Number, min: 1, max: 100, default: 10 }, maximumSourcesPerTask: { type: Number, min: 1, max: 20, default: 5 }, maximumPagesPerTask: { type: Number, min: 1, max: 1000, default: 25 }, maximumRecordsPerTask: { type: Number, min: 1, max: 10000, default: 500 }, maximumDepth: { type: Number, min: 0, max: 5, default: 1 }, maximumResponseBytes: { type: Number, min: 1024, max: 2000000, default: 500000 }, maximumTotalBytesPerTask: { type: Number, min: 1024, max: 20000000, default: 5000000 }, requestTimeoutSeconds: { type: Number, min: 5, max: 60, default: 15 }, minimumDelayMilliseconds: { type: Number, min: 0, max: 60000, default: 1000 }, maximumConcurrentRequests: { type: Number, min: 1, max: 4, default: 1 }, maximumRequestsPerMinute: { type: Number, min: 1, max: 600, default: 30 }, maximumRequestsPerDay: { type: Number, min: 1, max: 100000, default: 2000 }, stopAfterRepeated403: { type: Number, min: 1, max: 10, default: 2 }, stopAfterRepeated429: { type: Number, min: 1, max: 10, default: 2 }, requireActiveSourceReview: { type: Boolean, default: true }, sourceReviewValidityDays: { type: Number, min: 1, max: 1095, default: 365 }, staleDataWarningDays: { type: Number, min: 1, max: 3650, default: 365 },
    allowPdfCollection: { type: Boolean, default: false, validate: { validator: (v) => v === false, message: "PDF collection is locked off" } }, allowPrivateProfileCollection: { type: Boolean, default: false, validate: { validator: (v) => v === false, message: "Private profile collection is locked off" } }, allowCaptchaBypass: { type: Boolean, default: false, validate: { validator: (v) => v === false, message: "CAPTCHA bypass is locked off" } }, allowLoginBypass: { type: Boolean, default: false, validate: { validator: (v) => v === false, message: "Login bypass is locked off" } }, allowProxyEvasion: { type: Boolean, default: false, validate: { validator: (v) => v === false, message: "Proxy evasion is locked off" } }, allowArbitraryUrlFetch: { type: Boolean, default: false, validate: { validator: (v) => v === false, message: "Arbitrary URL fetching is locked off" } }, allowExternalFormSubmission: { type: Boolean, default: false, validate: { validator: (v) => v === false, message: "External form submission is locked off" } }, allowAutomaticOutreach: { type: Boolean, default: false, validate: { validator: (v) => v === false, message: "Automatic outreach is locked off" } }, allowUnapprovedApiCall: { type: Boolean, default: false, validate: { validator: (v) => v === false, message: "Unapproved API calls are locked off" } }, allowSourcePolicyOverrideByAgent: { type: Boolean, default: false, validate: { validator: (v) => v === false, message: "Source policy override is locked off" } },
    updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "Admin", default: null },
  },
  { timestamps: true, collection: "og_agent_settings" }
);

export default mongoose.model("OGAgentSettings", ogAgentSettingsSchema);
