import mongoose from "mongoose";

export const OG_RESEARCH_SOURCE_TYPES = ["PUBLIC_WEBSITE", "GOVERNMENT_WEBSITE", "PUBLIC_DIRECTORY", "APPROVED_API", "PARTNER_API", "COMPANY_OWNED_WEBSITE", "COMPANY_OWNED_FORM", "PUBLIC_DATASET", "SEARCH_API", "OTHER"];
export const OG_RESEARCH_SOURCE_STATUSES = ["DRAFT", "WAITING_APPROVAL", "ACTIVE", "PAUSED", "BLOCKED", "EXPIRED", "ARCHIVED"];
export const OG_RESEARCH_OPERATIONS = ["SEARCH", "FETCH_PAGE", "FETCH_API", "EXTRACT_BUSINESS_DATA", "EXTRACT_PUBLIC_CONTACT", "EXTRACT_PRICE_DATA", "EXTRACT_MARKET_DATA", "EXPORT", "CREATE_LEAD_CANDIDATE"];

const schema = new mongoose.Schema({
  name: { type: String, required: true, trim: true, maxlength: 200 }, description: { type: String, trim: true, maxlength: 4000, default: "" },
  sourceType: { type: String, enum: OG_RESEARCH_SOURCE_TYPES, required: true, index: true }, domain: { type: String, required: true, lowercase: true, trim: true, maxlength: 253, index: true },
  baseUrl: { type: String, trim: true, maxlength: 2000, default: "" }, apiBaseUrl: { type: String, trim: true, maxlength: 2000, default: "" }, connectorKey: { type: String, trim: true, maxlength: 120, default: "" }, secretReference: { type: String, trim: true, maxlength: 160, default: "" },
  country: { type: String, trim: true, maxlength: 120, default: "India" }, states: { type: [String], default: [] }, categories: { type: [String], default: [] }, supportedResearchTypes: { type: [String], default: [] },
  status: { type: String, enum: OG_RESEARCH_SOURCE_STATUSES, default: "DRAFT", index: true }, accessMode: { type: String, enum: ["PUBLIC", "API_KEY", "OAUTH", "PARTNER_CREDENTIAL", "INTERNAL", "MANUAL_UPLOAD"], default: "PUBLIC" },
  robotsPolicy: { type: String, enum: ["REQUIRED", "NOT_APPLICABLE", "MANUAL_REVIEW", "DISALLOW_AUTOMATION"], default: "REQUIRED" }, termsReviewStatus: { type: String, enum: ["NOT_REVIEWED", "REVIEWED_ALLOWED", "REVIEWED_RESTRICTED", "REVIEWED_PROHIBITED", "EXPIRED"], default: "NOT_REVIEWED", index: true },
  allowedOperations: { type: [{ type: String, enum: OG_RESEARCH_OPERATIONS }], default: [] }, prohibitedOperations: { type: [String], default: [] }, allowedPaths: { type: [String], default: ["/"] }, deniedPaths: { type: [String], default: ["/login", "/account", "/admin", "/checkout", "/payment"] }, allowedApiEndpoints: { type: [String], default: [] }, allowedQueryParameters: { type: [String], default: [] },
  maximumRequestsPerMinute: { type: Number, min: 1, max: 600, default: 10 }, maximumRequestsPerDay: { type: Number, min: 1, max: 100000, default: 500 }, maximumPagesPerTask: { type: Number, min: 1, max: 1000, default: 10 }, maximumRecordsPerTask: { type: Number, min: 1, max: 10000, default: 100 }, minimumDelayMilliseconds: { type: Number, min: 0, max: 60000, default: 1000 },
  followRedirects: { type: Boolean, default: false }, maximumRedirects: { type: Number, min: 0, max: 5, default: 0 }, allowContactExtraction: { type: Boolean, default: false }, allowPersonalContactExtraction: { type: Boolean, default: false }, allowBusinessContactExtraction: { type: Boolean, default: true }, allowLeadCreation: { type: Boolean, default: false }, allowRawContentStorage: { type: Boolean, default: false },
  evidenceRetentionDays: { type: Number, min: 1, max: 3650, default: 365 }, dataRetentionDays: { type: Number, min: 1, max: 3650, default: 180 }, sourceReliability: { type: String, enum: ["OFFICIAL", "HIGH", "MEDIUM", "LOW", "UNKNOWN"], default: "UNKNOWN", index: true },
  legalReviewNote: { type: String, trim: true, maxlength: 4000, default: "" }, privacyReviewNote: { type: String, trim: true, maxlength: 4000, default: "" }, configuredBy: { type: mongoose.Schema.Types.ObjectId, ref: "Admin", required: true }, approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: "Admin", default: null }, approvedAt: { type: Date, default: null }, lastReviewedAt: { type: Date, default: null }, reviewExpiresAt: { type: Date, default: null, index: true },
  lastHealthCheckAt: { type: Date, default: null }, lastSuccessfulAccessAt: { type: Date, default: null }, lastFailureAt: { type: Date, default: null }, failureCount: { type: Number, min: 0, default: 0 }, disabledReason: { type: String, trim: true, maxlength: 2000, default: "" }, policyVersion: { type: Number, min: 1, default: 1 }, approvalId: { type: mongoose.Schema.Types.ObjectId, ref: "OGAgentApproval", default: null },
}, { timestamps: true, collection: "og_research_sources" });
schema.index({ domain: 1, status: 1 });
export default mongoose.model("OGResearchSource", schema);
