import mongoose from "mongoose";
const planSchema = new mongoose.Schema({ sourceId: { type: mongoose.Schema.Types.ObjectId, ref: "OGResearchSource", required: true }, sourceName: String, reliability: String, operations: [String], urls: [String], endpointKeys: [String], queries: [String], maximumPages: Number, maximumRecords: Number, restrictions: [String], policyVersion: Number }, { _id: false });
const schema = new mongoose.Schema({
  taskId: { type: mongoose.Schema.Types.ObjectId, ref: "OGAgentTask", required: true, unique: true }, researchType: { type: String, required: true, trim: true, maxlength: 120, index: true }, title: { type: String, required: true, trim: true, maxlength: 200 }, purpose: { type: String, required: true, trim: true, maxlength: 4000 }, sourceIds: [{ type: mongoose.Schema.Types.ObjectId, ref: "OGResearchSource" }],
  countries: [String], states: [String], districts: [String], fruits: [String], businessCategories: [String], keywords: [String], dateFrom: Date, dateTo: Date,
  maximumPages: { type: Number, min: 1, max: 1000, default: 10 }, maximumRecords: { type: Number, min: 1, max: 10000, default: 100 }, maximumDepth: { type: Number, min: 0, max: 5, default: 0 }, contactExtractionRequested: { type: Boolean, default: false }, leadCandidateCreationRequested: { type: Boolean, default: false }, reportOnly: { type: Boolean, default: true },
  status: { type: String, enum: ["DRAFT", "PLANNING", "WAITING_APPROVAL", "QUEUED", "COLLECTING", "EXTRACTING", "DEDUPLICATING", "REVIEW_READY", "WAITING_IMPORT_APPROVAL", "COMPLETED", "PARTIAL", "FAILED", "CANCELLED"], default: "DRAFT", index: true }, sourcePlan: { type: [planSchema], default: [] },
  progress: { sourcesTotal: { type: Number, default: 0 }, sourcesCompleted: { type: Number, default: 0 }, pagesPlanned: { type: Number, default: 0 }, pagesFetched: { type: Number, default: 0 }, recordsExtracted: { type: Number, default: 0 }, uniqueRecords: { type: Number, default: 0 }, duplicates: { type: Number, default: 0 }, blockedRequests: { type: Number, default: 0 }, failedRequests: { type: Number, default: 0 }, warnings: { type: [String], default: [] } },
  resultSummary: { type: String, trim: true, maxlength: 12000, default: "" }, failureReason: { type: String, trim: true, maxlength: 4000, default: "" }, approvalId: { type: mongoose.Schema.Types.ObjectId, ref: "OGAgentApproval", default: null }, importApprovalId: { type: mongoose.Schema.Types.ObjectId, ref: "OGAgentApproval", default: null }, runLock: { type: String, default: "" }, policySnapshotHash: { type: String, default: "" }, startedAt: Date, completedAt: Date, requestedBy: { type: mongoose.Schema.Types.ObjectId, ref: "Admin", required: true },
}, { timestamps: true, collection: "og_research_tasks" });
schema.index({ status: 1, createdAt: -1 });
export default mongoose.model("OGResearchTask", schema);
