import { randomUUID } from "node:crypto";
import OGAgentApproval from "../../../models/OGAgentApproval.js";
import OGAgentTask from "../../../models/OGAgentTask.js";
import OGResearchRecord from "../../../models/OGResearchRecord.js";
import OGResearchTask from "../../../models/OGResearchTask.js";
import { buildResearchPlan } from "./researchPlannerService.js";
import { executeResearchSourcePlan } from "./researchFetchService.js";
import { checkResearchTaskDuplicates } from "./researchDuplicateService.js";
export const createResearchTask = async ({ input, actorId }) => { const task = await OGAgentTask.create({ title: input.title, taskType: "PUBLIC_RESEARCH", prompt: input.purpose, requestedBy: actorId, status: "DRAFT", riskLevel: input.contactExtractionRequested ? "HIGH" : "LOW" }); return OGResearchTask.create({ ...input, taskId: task._id, requestedBy: actorId, status: "DRAFT" }); };
export const planResearchTask = async ({ researchTask, actorId, settings }) => { researchTask.status = "PLANNING"; await researchTask.save(); const result = await buildResearchPlan({ task: researchTask, actorId, settings }); await OGAgentTask.updateOne({ _id: researchTask.taskId }, { $set: { status: result.approval ? "WAITING_APPROVAL" : "QUEUED", riskLevel: researchTask.contactExtractionRequested ? "HIGH" : result.plan.length > 1 ? "MEDIUM" : "LOW", plan: result.plan.map((item, index) => ({ stepNumber: index + 1, title: `Research ${item.sourceName}`, description: `${item.operations.join(", ")} within approved source policy`, tool: item.operations[0] === "FETCH_API" ? "research_api_fetch" : "research_website_fetch", riskLevel: researchTask.contactExtractionRequested ? "HIGH" : "MEDIUM", approvalRequired: Boolean(result.approval), status: "PENDING" })) } }); return result; };
export const runResearchTask = async ({ researchTaskId, settings, dependencies = {} }) => { const lock = randomUUID(); const task = await OGResearchTask.findOneAndUpdate({ _id: researchTaskId, status: { $in: ["QUEUED", "WAITING_APPROVAL", "PARTIAL", "FAILED"] }, runLock: "" }, { $set: { runLock: lock, status: "COLLECTING", startedAt: new Date(), failureReason: "" } }, { new: true }); if (!task) throw Object.assign(new Error("Research task is already running or cannot run from its current state"), { statusCode: 409, code: "RESEARCH_TASK_LOCKED" }); if (task.approvalId) { const approval = await OGAgentApproval.findById(task.approvalId); if (!approval || approval.status !== "APPROVED" || approval.actionPreview?.policySnapshotHash !== task.policySnapshotHash) { await OGResearchTask.updateOne({ _id: task._id, runLock: lock }, { $set: { status: "WAITING_APPROVAL", runLock: "" } }); throw Object.assign(new Error("The exact approved research plan is required"), { statusCode: 409, code: "RESEARCH_APPROVAL_REQUIRED" }); } if ((approval.conditions || []).some((condition) => !condition.satisfied)) throw Object.assign(new Error("Research approval conditions are unmet"), { statusCode: 409, code: "APPROVAL_CONDITIONS_UNMET" }); }
  try { for (const plan of task.sourcePlan) await executeResearchSourcePlan({ task, plan, settings, dependencies }); task.status = "DEDUPLICATING"; await task.save(); const duplicateSummary = await checkResearchTaskDuplicates(task._id); const records = await OGResearchRecord.countDocuments({ researchTaskId: task._id }); const fetches = await (await import("../../../models/OGResearchFetchRecord.js")).default.find({ researchTaskId: task._id }).lean(); task.progress.sourcesCompleted = task.sourcePlan.length; task.progress.pagesFetched = fetches.filter((item) => item.status === "FETCHED").length; task.progress.recordsExtracted = records; task.progress.duplicates = duplicateSummary.duplicates; task.progress.uniqueRecords = duplicateSummary.unique; task.progress.blockedRequests = fetches.filter((item) => item.status === "BLOCKED").length; task.progress.failedRequests = fetches.filter((item) => ["FAILED", "RATE_LIMITED"].includes(item.status)).length; task.status = records ? "REVIEW_READY" : fetches.some((item) => item.status === "FETCHED") ? "PARTIAL" : "FAILED"; task.resultSummary = `${records} temporary records extracted; ${duplicateSummary.duplicates} require duplicate review. No permanent lead or outreach was created.`; task.completedAt = new Date(); task.runLock = ""; await task.save(); await OGAgentTask.updateOne({ _id: task.taskId }, { $set: { status: task.status === "FAILED" ? "FAILED" : "COMPLETED", result: { summary: task.resultSummary, data: { researchTaskId: task._id, progress: task.progress }, recommendations: ["Review evidence and privacy warnings.", "Request separate approval before import."] }, completedAt: new Date() } }); return task; } catch (cause) { await OGResearchTask.updateOne({ _id: task._id, runLock: lock }, { $set: { status: "FAILED", failureReason: String(cause.message).slice(0, 4000), runLock: "", completedAt: new Date() } }); throw cause; }
};
export const cancelResearchTask = (id) => OGResearchTask.findOneAndUpdate({ _id: id, status: { $nin: ["COMPLETED", "CANCELLED"] } }, { $set: { status: "CANCELLED", runLock: "", completedAt: new Date() } }, { new: true });
