import { createHash } from "node:crypto";
import OGAgentApproval from "../../../models/OGAgentApproval.js";
import OGResearchSource from "../../../models/OGResearchSource.js";
import { assertResearchSourceAllowed, sourcePolicyHash } from "./researchSourcePolicyService.js";
import { getBoundedImprovementContext } from "../improvement/retrievalContextService.js";
export const buildResearchPlan = async ({ task, actorId, settings }) => { const sources = await OGResearchSource.find({ _id: { $in: task.sourceIds } }); if (sources.length !== task.sourceIds.length) throw Object.assign(new Error("One or more research sources were not found"), { statusCode: 400, code: "SOURCE_NOT_FOUND" }); if (sources.length > settings.maximumSourcesPerTask) throw Object.assign(new Error("Research source count exceeds the configured limit"), { statusCode: 400, code: "RESEARCH_LIMIT_EXCEEDED" });
  const sourcePlan = sources.map((source) => { const operation = ["APPROVED_API", "PARTNER_API", "SEARCH_API"].includes(source.sourceType) ? "FETCH_API" : "FETCH_PAGE"; assertResearchSourceAllowed({ source, operation, task }); return { sourceId: source._id, sourceName: source.name, reliability: source.sourceReliability, operations: [operation, "EXTRACT_BUSINESS_DATA"], urls: operation === "FETCH_PAGE" ? [source.baseUrl] : [], endpointKeys: operation === "FETCH_API" ? source.allowedApiEndpoints.slice(0, 1) : [], queries: task.keywords, maximumPages: Math.min(task.maximumPages, source.maximumPagesPerTask), maximumRecords: Math.min(task.maximumRecords, source.maximumRecordsPerTask), restrictions: [...source.prohibitedOperations, source.allowContactExtraction ? "Public business contact extraction only" : "No contact extraction"], policyVersion: source.policyVersion }; });
  const context = await getBoundedImprovementContext({ taskType: "PUBLIC_RESEARCH", tool: "research_plan_generate", limit: 3 }).catch(() => ({ appliedIds: [] })); const approvalRequired = task.contactExtractionRequested || task.maximumPages > settings.requireApprovalAbovePageLimit || sources.length > 1 || sources.some((s) => ["LOW", "UNKNOWN"].includes(s.sourceReliability)); task.sourcePlan = sourcePlan; task.progress.sourcesTotal = sources.length; task.progress.pagesPlanned = sourcePlan.reduce((n, item) => n + Math.min(item.urls.length || item.endpointKeys.length, item.maximumPages), 0); task.policySnapshotHash = createHash("sha256").update(sourcePlan.map((item) => `${item.sourceId}:${item.policyVersion}:${sourcePolicyHash(sources.find((s) => String(s._id) === String(item.sourceId)))}`).join("|")).digest("hex"); task.status = approvalRequired ? "WAITING_APPROVAL" : "QUEUED"; await task.save();
  let approval = null; if (approvalRequired) { approval = await OGAgentApproval.findOneAndUpdate({ subjectKey: `RESEARCH_TASK:${task._id}`, actionType: "RESEARCH_PLAN_EXECUTION", status: "PENDING" }, { $setOnInsert: { taskId: task.taskId, subjectType: "RESEARCH_TASK", subjectId: task._id, subjectKey: `RESEARCH_TASK:${task._id}`, requestedBy: actorId, actionType: "RESEARCH_PLAN_EXECUTION", actionTitle: `Approve controlled research plan: ${task.title}`, actionDescription: "Allows only the displayed approved sources, limits, public-contact policy, and exact policy versions. It does not authorize import or outreach.", actionPreview: { purpose: task.purpose, sources: sourcePlan, maximumPages: task.maximumPages, maximumRecords: task.maximumRecords, contactExtractionRequested: task.contactExtractionRequested, leadCandidateCreationRequested: task.leadCandidateCreationRequested, reportOnly: task.reportOnly, humanImpact: { benefits: "Business and market research", harms: "Possible outdated or unwanted contact use", affectedGroups: ["growers", "buyers", "employees"], safeguards: ["pilot limits", "manual review", "duplicate checks", "no outreach"] }, policySnapshotHash: task.policySnapshotHash, guidanceApplied: context.appliedIds }, riskLevel: task.contactExtractionRequested ? "HIGH" : "MEDIUM", status: "PENDING" } }, { upsert: true, new: true, runValidators: true }); task.approvalId = approval._id; await task.save(); }
  return { task, approval, plan: sourcePlan };
};
