import { createHash } from "node:crypto";
import OGResearchFetchRecord from "../../../models/OGResearchFetchRecord.js";
import OGResearchRecord from "../../../models/OGResearchRecord.js";
import OGResearchSource from "../../../models/OGResearchSource.js";
import { fetchApprovedWebsitePage } from "./researchWebsiteAdapter.js";
import { fetchApprovedApi } from "./researchApiAdapter.js";
import { getRobotsDecision } from "./researchRobotsService.js";
import { claimResearchRequest, recordResearchBlockingResponse } from "./researchRateLimitService.js";
import { assertResearchSourceAllowed, sourcePolicyHash } from "./researchSourcePolicyService.js";
import { extractResearchRecords } from "./researchContentExtractor.js";
import { normalizeResearchRecord } from "./researchRecordNormalizer.js";
import { auditResearchEvent } from "./researchAuditService.js";
const keyFor = (value) => createHash("sha256").update(String(value)).digest("hex");
export const executeResearchSourcePlan = async ({ task, plan, settings, dependencies = {} }) => { const source = await OGResearchSource.findById(plan.sourceId); const operation = plan.operations[0]; assertResearchSourceAllowed({ source, operation, task }); if (source.policyVersion !== plan.policyVersion) throw Object.assign(new Error("Source policy changed after planning"), { statusCode: 409, code: "SOURCE_POLICY_CHANGED" }); const targets = operation === "FETCH_API" ? plan.endpointKeys : plan.urls; const output = [];
  for (const target of targets.slice(0, plan.maximumPages)) { const refreshedTask = await task.constructor.findById(task._id); if (refreshedTask.status === "CANCELLED") break; const requestUrl = operation === "FETCH_API" ? new URL(target, source.apiBaseUrl || source.baseUrl).toString() : target; const normalizedUrlKey = keyFor(requestUrl); let fetchRecord = await OGResearchFetchRecord.findOneAndUpdate({ researchTaskId: task._id, sourceId: source._id, normalizedUrlKey }, { $setOnInsert: { researchTaskId: task._id, sourceId: source._id, requestType: operation === "FETCH_API" ? "API_REQUEST" : "WEBSITE_PAGE", requestUrl, normalizedUrl: requestUrl, normalizedUrlKey, endpointKey: operation === "FETCH_API" ? target : "", status: "PLANNED", policyDecision: "PENDING" } }, { upsert: true, new: true }); if (fetchRecord.status === "FETCHED") { output.push(fetchRecord); continue; }
    const release = claimResearchRequest({ source, globalSettings: settings }); const started = Date.now(); try { fetchRecord.status = "FETCHING"; await fetchRecord.save(); let result; let robots = { allowed: true, reason: "API_POLICY", crawlDelayMs: 0 }; if (operation === "FETCH_PAGE") { robots = await getRobotsDecision({ url: new URL(requestUrl), source, fetchText: async (robotsUrl) => (await fetchApprovedWebsitePage({ source: { ...source.toObject(), allowedPaths: ["/robots.txt"] }, value: robotsUrl, settings, ...dependencies })).rawContent }); if (!robots.allowed) throw Object.assign(new Error("robots.txt disallows this path"), { code: "ROBOTS_DISALLOWED", statusCode: 403 }); result = await fetchApprovedWebsitePage({ source, value: requestUrl, settings, ...dependencies }); } else result = await fetchApprovedApi({ source, endpointKey: target, query: Object.fromEntries((task.keywords || []).slice(0, 1).map((value) => [source.allowedQueryParameters[0], value]).filter(([key]) => key)), settings, ...dependencies }); const raw = result.rawContent || JSON.stringify(result.data); fetchRecord.status = "FETCHED"; fetchRecord.httpStatus = result.httpStatus; fetchRecord.contentType = result.contentType; fetchRecord.contentLength = Buffer.byteLength(raw); fetchRecord.redirectChain = result.redirectChain || []; fetchRecord.fetchedAt = new Date(); fetchRecord.durationMilliseconds = Date.now() - started; fetchRecord.robotsAllowed = robots.allowed; fetchRecord.policyDecision = "ALLOWED"; fetchRecord.policyReason = result.injectionDetected ? "SOURCE_INJECTION_DETECTED_AND_REMOVED" : robots.reason; fetchRecord.contentHash = result.contentHash || keyFor(raw); fetchRecord.safeContentPreview = result.safeText || String(raw).slice(0, 12000); fetchRecord.extractionStatus = "EXTRACTING"; await fetchRecord.save(); const extracted = extractResearchRecords({ safeText: fetchRecord.safeContentPreview, rawContent: raw, source, task, fetchRecord }).slice(0, plan.maximumRecords); for (const record of extracted) await OGResearchRecord.create(normalizeResearchRecord(record)); fetchRecord.extractionStatus = "COMPLETED"; await fetchRecord.save(); source.lastSuccessfulAccessAt = new Date(); source.failureCount = 0; await source.save(); await auditResearchEvent({ taskId: task.taskId, actorId: task.requestedBy, eventType: "RESEARCH_FETCH_ALLOWED", action: "Fetched approved research target", metadata: { sourceId: source._id, fetchRecordId: fetchRecord._id, requestType: fetchRecord.requestType, policyDecision: fetchRecord.policyDecision, httpStatus: fetchRecord.httpStatus } }); output.push(fetchRecord);
    } catch (error) { const stop = recordResearchBlockingResponse(source._id, error.statusCode, settings); fetchRecord.status = error.statusCode === 429 ? "RATE_LIMITED" : ["ROBOTS_DISALLOWED", "CAPTCHA_DETECTED", "LOGIN_REQUIRED", "SSRF_BLOCKED", "REDIRECT_BLOCKED"].includes(error.code) ? "BLOCKED" : "FAILED"; fetchRecord.errorType = error.code || "FETCH_FAILED"; fetchRecord.errorSummary = String(error.message).slice(0, 1000); fetchRecord.policyDecision = "BLOCKED"; fetchRecord.policyReason = error.code || "FETCH_FAILED"; await fetchRecord.save(); source.failureCount += 1; source.lastFailureAt = new Date(); if (stop) { source.status = "PAUSED"; source.disabledReason = `Repeated blocking response: ${error.code}`; } await source.save(); await auditResearchEvent({ taskId: task.taskId, actorId: task.requestedBy, eventType: "RESEARCH_FETCH_BLOCKED", action: "Blocked or failed research target", details: fetchRecord.errorSummary, metadata: { sourceId: source._id, fetchRecordId: fetchRecord._id, requestType: fetchRecord.requestType, policyDecision: fetchRecord.policyDecision, policyReason: fetchRecord.policyReason, httpStatus: error.statusCode || null, sourcePaused: stop } }); output.push(fetchRecord); } finally { release(); }
  }
  return output;
};
