import OGAgentApproval from "../../../models/OGAgentApproval.js";
import OGAgentLeadCandidate from "../../../models/OGAgentLeadCandidate.js";
import BusinessLead from "../../../models/BusinessLead.js";
import OGResearchTask from "../../../models/OGResearchTask.js";
import OGAgentTask from "../../../models/OGAgentTask.js";
import { buildCandidateFingerprint } from "../email/emailLeadImportService.js";
export const requestResearchImportApproval = async ({ researchTask, actorId }) => { const candidates = await OGAgentLeadCandidate.find({ researchTaskId: researchTask._id, selectedForImport: true, importStatus: { $in: ["SELECTED", "NOT_SELECTED"] }, importEligibility: "ELIGIBLE", duplicateStatus: "UNIQUE" }); if (!candidates.length) throw Object.assign(new Error("Select at least one eligible unique research candidate"), { statusCode: 400, code: "NO_SELECTED_CANDIDATES" }); const snapshots = candidates.map((item) => ({ candidateId: String(item._id), updatedAt: new Date(item.updatedAt).toISOString(), fingerprint: buildCandidateFingerprint(item.toObject()) })); const approval = await OGAgentApproval.findOneAndUpdate({ subjectKey: `RESEARCH_IMPORT:${researchTask._id}`, actionType: "RESEARCH_LEAD_IMPORT", status: "PENDING" }, { $setOnInsert: { taskId: researchTask.taskId, subjectType: "RESEARCH_IMPORT", subjectId: researchTask._id, subjectKey: `RESEARCH_IMPORT:${researchTask._id}`, requestedBy: actorId, actionType: "RESEARCH_LEAD_IMPORT", actionTitle: `Import ${candidates.length} reviewed research lead candidates`, actionDescription: "Imports only the immutable approved snapshot as unverified BusinessLead records. No account or outreach is created.", actionPreview: { researchTaskId: String(researchTask._id), candidateSnapshots: snapshots, automaticOutreach: false, accountsCreated: false }, riskLevel: "HIGH", status: "PENDING" } }, { upsert: true, new: true, runValidators: true }); await OGAgentLeadCandidate.updateMany({ _id: { $in: candidates.map((item) => item._id) } }, { $set: { importStatus: "WAITING_APPROVAL" } }); researchTask.status = "WAITING_IMPORT_APPROVAL"; researchTask.importApprovalId = approval._id; await Promise.all([researchTask.save(), OGAgentTask.updateOne({ _id: researchTask.taskId }, { $set: { status: "WAITING_APPROVAL" } })]); return approval; };
export const importApprovedResearchCandidates = async ({ researchTaskId, actorId }) => { const task = await OGResearchTask.findById(researchTaskId); const approval = await OGAgentApproval.findOne({ _id: task?.importApprovalId, actionType: "RESEARCH_LEAD_IMPORT", status: "APPROVED", consumedAt: null }); if (!task || !approval) throw Object.assign(new Error("Approved research import snapshot is required"), { statusCode: 409, code: "IMPORT_NOT_APPROVED" }); if ((approval.conditions || []).some((item) => !item.satisfied)) throw Object.assign(new Error("Import approval conditions are unmet"), { statusCode: 409, code: "APPROVAL_CONDITIONS_UNMET" }); const snapshots = approval.actionPreview?.candidateSnapshots || []; const candidates = await OGAgentLeadCandidate.find({ _id: { $in: snapshots.map((item) => item.candidateId) }, researchTaskId: task._id }); if (candidates.length !== snapshots.length || candidates.some((item) => { const snap = snapshots.find((s) => s.candidateId === String(item._id)); return !snap || snap.fingerprint !== buildCandidateFingerprint(item.toObject()) || new Date(item.updatedAt).toISOString() !== snap.updatedAt; })) throw Object.assign(new Error("Research import snapshot changed; request fresh approval"), { statusCode: 409, code: "APPROVAL_SNAPSHOT_CHANGED" });
  const claimed = await OGAgentApproval.findOneAndUpdate({ _id: approval._id, status: "APPROVED", consumedAt: null }, { $set: { consumedAt: new Date(), consumedBy: actorId } }, { new: true }); if (!claimed) throw Object.assign(new Error("Approval was consumed concurrently"), { statusCode: 409, code: "APPROVAL_ALREADY_CONSUMED" }); const results = [];
  for (const candidate of candidates) { if (candidate.importStatus === "IMPORTED") { results.push({ candidateId: candidate._id, status: "SKIPPED", reason: "Already imported" }); continue; } const d = candidate.extractedData; const lead = await BusinessLead.create({ leadType: candidate.suggestedLeadType, status: "UNVERIFIED", ...(d.toObject?.() || d), sourceType: candidate.sourceType === "API" ? "API" : "WEBSITE", sourceReference: candidate.source.sourceReference, sourceEvidence: candidate.source.evidenceSnippet, extractionTaskId: task.taskId, sourceCandidateId: candidate._id, classificationConfidence: candidate.fieldConfidence?.leadType || candidate.overallConfidence, overallConfidence: candidate.overallConfidence, verificationStatus: "MANUAL_REVIEW_REQUIRED", consentStatus: candidate.businessContactContext === "BUSINESS_CONTACT" ? "BUSINESS_CONTACT" : "UNKNOWN", duplicateStatus: "UNIQUE", importedBy: actorId, importedAt: new Date(), createdByType: "OG_AGENT", tags: ["research-agent", "public-source", "no-automatic-outreach"] }); candidate.importStatus = "IMPORTED"; candidate.importedLeadId = lead._id; await candidate.save(); results.push({ candidateId: candidate._id, leadId: lead._id, status: "IMPORTED" }); }
  task.status = "COMPLETED"; task.completedAt = new Date(); await task.save(); return { imported: results.filter((item) => item.status === "IMPORTED").length, results };
};
