import OGAgentLeadCandidate from "../../../models/OGAgentLeadCandidate.js";
import OGResearchRecord from "../../../models/OGResearchRecord.js";
import OGResearchSource from "../../../models/OGResearchSource.js";
import { buildNormalizedCandidateData } from "../email/emailLeadNormalizationService.js";
const eligible = new Set(["GROWER", "BUYER", "TRADER", "FPO", "COOPERATIVE", "LOGISTICS_PROVIDER", "COLD_STORAGE", "PACK_HOUSE", "PROCESSING_UNIT", "BUSINESS_DIRECTORY_ENTRY"]);
const leadType = (type) => type === "GROWER" ? "GROWER" : type === "LOGISTICS_PROVIDER" || type === "COLD_STORAGE" || type === "PACK_HOUSE" || type === "PROCESSING_UNIT" ? "LOGISTICS" : "BUYER";
export const createResearchLeadCandidates = async ({ researchTask, recordIds = [], actorId }) => { const filter = { researchTaskId: researchTask._id, status: { $in: ["APPROVED", "EXTRACTED"] }, selectedForLeadCandidate: true }; if (recordIds.length) filter._id = { $in: recordIds }; const records = await OGResearchRecord.find(filter); const created = []; const skipped = [];
  for (const record of records) { const source = await OGResearchSource.findById(record.sourceId); const reason = !eligible.has(record.recordType) ? "Record type is not lead-eligible" : !source?.allowLeadCreation ? "Source does not allow lead creation" : ["PERSONAL_CONTACT", "UNCERTAIN"].includes(record.contactContext) ? "Contact context requires manual privacy review" : record.duplicateStatus !== "UNIQUE" ? "Potential duplicate" : ""; if (reason) { skipped.push({ recordId: record._id, reason }); continue; }
    const extractedData = { name: record.name || "", businessName: record.businessName || record.organizationName || record.name || "", contactPerson: record.contactPerson || "", email: record.publicBusinessEmail || "", phone: record.publicBusinessPhone || "", address: record.address || "", village: record.village || "", tehsil: record.tehsil || "", district: record.district || "", state: record.state || "", postalCode: record.postalCode || "", country: record.country || "India", fruits: record.fruits || [], businessCategories: record.businessCategories || [] };
    const candidate = await OGAgentLeadCandidate.findOneAndUpdate({ researchRecordId: record._id }, { $setOnInsert: { extractionId: null, researchTaskId: researchTask._id, researchRecordId: record._id, researchSourceId: source._id, sourceType: source.sourceType.includes("API") ? "API" : "RESEARCH", taskId: researchTask.taskId, suggestedLeadType: leadType(record.recordType), extractedData, normalizedData: buildNormalizedCandidateData(extractedData), overallConfidence: record.overallConfidence, classificationExplanation: `Research record ${record.recordType} from ${source.sourceReliability} source`, source: { mailbox: "research", sourceReference: record.sourceEvidence?.[0]?.sourceUrl || String(record._id), subject: record.sourceEvidence?.[0]?.sourceTitle || source.name, evidenceSnippet: record.sourceEvidence?.[0]?.evidenceSnippet || "" }, duplicateMatches: record.duplicateMatches, duplicateStatus: record.duplicateStatus, warnings: record.warnings, validationErrors: record.validationErrors, businessContactContext: record.contactContext, publicContactBasis: "Published on the approved public business source retained in source evidence.", sourceReliability: record.sourceReliability, importEligibility: "ELIGIBLE", privacyWarnings: [record.privacyWarning].filter(Boolean), selectedForImport: false, importStatus: "NOT_SELECTED", reviewedBy: actorId, reviewedAt: new Date() } }, { upsert: true, new: true, runValidators: true }); record.status = "CONVERTED_TO_LEAD_CANDIDATE"; await record.save(); created.push(candidate); }
  return { created, skipped };
};
