const warning = "Do not promise guaranteed sales, prices, employment, investment returns, government benefits, or payment outcomes.";
const prohibited = ["Guaranteed income, buyer, sale, or price", "Government affiliation or benefit claims", "Loans, investment returns, legal commitments, or employment promises", "Payment, OTP, password, bank, or Razorpay credential requests", "Fake deadlines, scarcity, or impersonation"];
export const generateSafeCallScript = ({ purpose = "LEAD_QUALIFICATION", leadType = "OTHER", language = "ENGLISH", lead = {}, previousOutcome = "", attemptNumber = 1 } = {}) => {
  const name = lead.name || lead.contactPerson || "the contact";
  const hindi = ["HINDI", "HINGLISH", "LOCAL_LANGUAGE"].includes(language);
  const introduction = hindi ? `नमस्कार, मैं Orchard Growers Private Limited की ओर से बात कर रहा/रही हूँ। क्या मैं ${name} जी से बात कर रहा/रही हूँ?` : `Hello, I am calling from Orchard Growers Private Limited. May I speak with ${name}?`;
  return { purpose, leadType, language, attemptNumber, previousOutcome, introduction, identityDisclosure: "State your real name and that you are a human staff member of Orchard Growers Private Limited. OG Agent is only showing preparation notes.", purposeStatement: hindi ? "हम eFruitMandi.live B2B fruit marketplace पर growers और bulk buyers को connect करने का कार्य करते हैं।" : `This is a human follow-up regarding ${purpose.replace(/_/g, " ").toLowerCase()} on the eFruitMandi.live B2B fruit marketplace.`, verificationQuestions: ["May I confirm your name and business?", "Is this the correct business contact number?", "Which location and fruits are relevant?"], qualificationQuestions: leadType === "BUYER" ? ["Which fruits, grades, quantities, and delivery locations do you require?", "What procurement frequency and packaging are relevant?"] : ["Which fruits do you grow or supply, and what is the expected season and volume?", "Which market locations and packaging are relevant?"], platformExplanation: "eFruitMandi.live supports B2B discovery between fruit growers and bulk buyers. Availability, price, quality, payment, and transactions require separate verification and agreement.", objectionResponses: [{ objection: "Send information first", response: "Certainly. I will record that request for a staff member to handle manually; OG Agent will not send a message." }, { objection: "Not interested", response: "Understood. May I record whether you prefer no future calls?" }], closingStatement: "Thank the contact, repeat only the mutually confirmed next step, and record the outcome manually.", prohibitedCommitments: prohibited, recommendedNextAction: previousOutcome === "NO_ANSWER" ? "Ask the telecaller to confirm a retry date." : "Record a user-confirmed outcome and next action.", complianceWarning: warning, externalActionPerformed: false };
};
export const CALL_SCRIPT_WARNING = warning;
