import type {
  OGAgentApiResponse,
  OGAgentApproval,
  OGAgentAuditLog,
  OGAgentSettings,
  OGAgentTask,
  OGAgentTaskDetails,
  OGAgentTaskType,
  OGAgentTool,
  OGAgentEmailSource,
  OGAgentLeadExtraction,
  OGAgentLeadCandidate,
  OGAgentBusinessLead,
  OGAgentLeadImportPreview,
  OGCallingCampaign,
  OGCallQueueItem,
  OGCallActivity,
  OGFollowUp,
  OGCallScript,
  OGCallingDashboard,
  OGAgentAdminReference,
  OGCallScriptTemplate,
  OGCodingTask,
  OGCodingTaskDetails,
  OGCodePatch,
  OGCodeCommand,
  OGCodeCommandRun,
  OGRepositoryStatus,
  OGCodingConfig,
  OGAgentFeedbackInput,
  OGAgentImprovementRecord,
  OGResearchSource,
  OGResearchTask,
  OGResearchRecord,
  OGResearchReport,
} from '../types/ogAgent';

type TaskInput = { title: string; taskType: OGAgentTaskType; prompt: string };

export const createOGAgentApi = (apiBase: string, authHeaders: Record<string, string>) => {
  const endpoint = `${apiBase}/admin/og-agent`;

  const request = async <T,>(path: string, init: RequestInit = {}) => {
    const response = await fetch(`${endpoint}${path}`, {
      ...init,
      headers: { ...authHeaders, ...(init.headers || {}) },
    });
    const body = await response.json().catch(() => ({})) as Partial<OGAgentApiResponse<T>>;
    if (!response.ok) throw new Error(body.message || body.msg || 'OG Agent request failed safely.');
    return body as OGAgentApiResponse<T>;
  };

  return {
    listTasks: () => request<OGAgentTask[]>('/tasks?limit=100'),
    getTask: (taskId: string) => request<OGAgentTaskDetails>(`/tasks/${encodeURIComponent(taskId)}`),
    createTask: (input: TaskInput) => request<OGAgentTask>('/tasks', { method: 'POST', body: JSON.stringify(input) }),
    planTask: (taskId: string) => request<{ task: OGAgentTask; approval?: OGAgentApproval | null }>(`/tasks/${encodeURIComponent(taskId)}/plan`, { method: 'POST' }),
    runTask: (taskId: string) => request<OGAgentTask>(`/tasks/${encodeURIComponent(taskId)}/run`, { method: 'POST' }),
    cancelTask: (taskId: string) => request<OGAgentTask>(`/tasks/${encodeURIComponent(taskId)}/cancel`, { method: 'POST' }),
    listApprovals: () => request<OGAgentApproval[]>('/approvals?status=PENDING&limit=100'),
    decideApproval: (approvalId: string, decision: 'approve' | 'reject', reviewerNote: string) =>
      request<{ approval: OGAgentApproval; task: OGAgentTask }>(`/approvals/${encodeURIComponent(approvalId)}/${decision}`, {
        method: 'POST',
        body: JSON.stringify({ reviewerNote }),
      }),
    submitStructuredFeedback: (input: OGAgentFeedbackInput) => request<{ feedback: OGAgentImprovementRecord; approval?: OGAgentApproval; drafts: OGAgentImprovementRecord[] }>('/feedback', { method: 'POST', body: JSON.stringify(input) }),
    listFeedback: () => request<OGAgentImprovementRecord[]>('/feedback?limit=100'),
    getTaskProposals: (taskId: string) => request<OGAgentImprovementRecord[]>(`/tasks/${encodeURIComponent(taskId)}/proposals`),
    listImprovementExamples: () => request<OGAgentImprovementRecord[]>('/improvement/examples?limit=100'),
    listImprovementGuidance: () => request<OGAgentImprovementRecord[]>('/improvement/guidance?limit=100'),
    listImprovementProposals: () => request<OGAgentImprovementRecord[]>('/improvement/proposals?limit=100'),
    listPromptVersions: () => request<OGAgentImprovementRecord[]>('/improvement/prompts?limit=100'),
    listRuleVersions: () => request<OGAgentImprovementRecord[]>('/improvement/rules?limit=100'),
    listEvaluationDatasets: () => request<OGAgentImprovementRecord[]>('/improvement/datasets?limit=100'),
    listEvaluationRuns: () => request<OGAgentImprovementRecord[]>('/improvement/evaluations?limit=100'),
    getImprovementMetrics: () => request<OGAgentImprovementRecord[]>('/improvement/metrics/summary'),
    getHumanImpactMetrics: () => request<OGAgentImprovementRecord[]>('/improvement/metrics/human-impact'),
    listResearchSources: () => request<OGResearchSource[]>('/research/sources?limit=100'),
    createResearchSource: (input: Record<string, unknown>) => request<OGResearchSource>('/research/sources', { method: 'POST', body: JSON.stringify(input) }),
    updateResearchSource: (id: string, input: Record<string, unknown>) => request<OGResearchSource>(`/research/sources/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify(input) }),
    requestResearchSourceApproval: (id: string) => request<OGAgentApproval>(`/research/sources/${encodeURIComponent(id)}/request-approval`, { method: 'POST' }),
    activateResearchSource: (id: string) => request<OGResearchSource>(`/research/sources/${encodeURIComponent(id)}/activate`, { method: 'POST' }),
    transitionResearchSource: (id: string, action: 'pause' | 'block', reason = '') => request<OGResearchSource>(`/research/sources/${encodeURIComponent(id)}/${action}`, { method: 'POST', body: JSON.stringify({ reason }) }),
    checkResearchSourceHealth: (id: string) => request<Record<string, unknown>>(`/research/sources/${encodeURIComponent(id)}/health-check`, { method: 'POST' }),
    listResearchSourceReviews: (id: string) => request<Record<string, unknown>[]>(`/research/sources/${encodeURIComponent(id)}/reviews?limit=100`),
    createResearchSourceReview: (id: string, input: Record<string, unknown>) => request<Record<string, unknown>>(`/research/sources/${encodeURIComponent(id)}/reviews`, { method: 'POST', body: JSON.stringify(input) }),
    listResearchTasks: () => request<OGResearchTask[]>('/research/tasks?limit=100'),
    createResearchTask: (input: Record<string, unknown>) => request<OGResearchTask>('/research/tasks', { method: 'POST', body: JSON.stringify(input) }),
    planResearchTask: (id: string) => request<{ task: OGResearchTask; approval?: OGAgentApproval; plan: unknown[] }>(`/research/tasks/${encodeURIComponent(id)}/plan`, { method: 'POST' }),
    runResearchTask: (id: string) => request<OGResearchTask>(`/research/tasks/${encodeURIComponent(id)}/run`, { method: 'POST' }),
    cancelResearchTask: (id: string) => request<OGResearchTask>(`/research/tasks/${encodeURIComponent(id)}/cancel`, { method: 'POST' }),
    listResearchRecords: (id: string) => request<OGResearchRecord[]>(`/research/tasks/${encodeURIComponent(id)}/records?limit=100`),
    updateResearchRecord: (id: string, input: Record<string, unknown>) => request<OGResearchRecord>(`/research/records/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify(input) }),
    checkResearchDuplicates: (id: string) => request<Record<string, number>>(`/research/tasks/${encodeURIComponent(id)}/check-duplicates`, { method: 'POST' }),
    createResearchLeadCandidates: (id: string, recordIds: string[]) => request<Record<string, unknown>>(`/research/tasks/${encodeURIComponent(id)}/create-lead-candidates`, { method: 'POST', body: JSON.stringify({ recordIds }) }),
    listResearchLeadCandidates: (id: string) => request<OGAgentLeadCandidate[]>(`/research/tasks/${encodeURIComponent(id)}/lead-candidates?limit=100`),
    selectResearchCandidates: (researchTaskId: string, candidateIds: string[], selectedForImport = true) => request<{ modified: number }>('/research/records/bulk-selection', { method: 'POST', body: JSON.stringify({ researchTaskId, candidateIds, selectedForImport }) }),
    requestResearchImport: (id: string) => request<OGAgentApproval>(`/research/tasks/${encodeURIComponent(id)}/request-import-approval`, { method: 'POST' }),
    importApprovedResearch: (id: string) => request<Record<string, unknown>>(`/research/tasks/${encodeURIComponent(id)}/import-approved`, { method: 'POST' }),
    generateResearchReport: (id: string) => request<OGResearchReport>(`/research/tasks/${encodeURIComponent(id)}/generate-report`, { method: 'POST' }),
    listResearchReports: () => request<OGResearchReport[]>('/research/reports?limit=100'),
    approveResearchReport: (id: string) => request<OGResearchReport>(`/research/reports/${encodeURIComponent(id)}/approve`, { method: 'POST' }),
    listAuditLogs: (taskId = '') => request<OGAgentAuditLog[]>(`/audit-logs?limit=50${taskId ? `&taskId=${encodeURIComponent(taskId)}` : ''}`),
    getSettings: () => request<OGAgentSettings>('/settings'),
    updateSettings: (settings: Partial<OGAgentSettings>) => request<OGAgentSettings>('/settings', {
      method: 'PATCH',
      body: JSON.stringify(settings),
    }),
    listTools: () => request<OGAgentTool[]>('/tools'),
    listEmailSources: () => request<OGAgentEmailSource[]>('/email/sources'),
    createEmailExtraction: (input: Record<string, unknown>) => request<OGAgentLeadExtraction>('/email/extractions', { method: 'POST', body: JSON.stringify(input) }),
    listEmailExtractions: () => request<OGAgentLeadExtraction[]>('/email/extractions?limit=100'),
    runEmailExtraction: (extractionId: string) => request<OGAgentLeadExtraction>(`/email/extractions/${encodeURIComponent(extractionId)}/run`, { method: 'POST' }),
    cancelEmailExtraction: (extractionId: string) => request<OGAgentLeadExtraction>(`/email/extractions/${encodeURIComponent(extractionId)}/cancel`, { method: 'POST' }),
    listLeadCandidates: (extractionId: string) => request<OGAgentLeadCandidate[]>(`/email/extractions/${encodeURIComponent(extractionId)}/candidates?limit=100`),
    getLeadCandidate: (candidateId: string) => request<OGAgentLeadCandidate>(`/email/candidates/${encodeURIComponent(candidateId)}`),
    updateLeadCandidate: (candidateId: string, input: Record<string, unknown>) => request<OGAgentLeadCandidate>(`/email/candidates/${encodeURIComponent(candidateId)}`, { method: 'PATCH', body: JSON.stringify(input) }),
    bulkSelectLeadCandidates: (extractionId: string, mode: 'VALID_UNIQUE' | 'CLEAR' | 'IDS', candidateIds: string[] = []) => request<{ selected: number }>('/email/candidates/bulk-selection', { method: 'POST', body: JSON.stringify({ extractionId, mode, candidateIds }) }),
    checkLeadDuplicates: (extractionId: string) => request<{ checked: number; unique: number; duplicates: number }>(`/email/extractions/${encodeURIComponent(extractionId)}/check-duplicates`, { method: 'POST' }),
    previewLeadImport: (extractionId: string) => request<{ extraction: { _id: string; taskId: string; sourceMailbox: string }; preview: OGAgentLeadImportPreview }>(`/email/extractions/${encodeURIComponent(extractionId)}/import-preview`, { method: 'POST' }),
    requestLeadImportApproval: (extractionId: string) => request<{ approval: OGAgentApproval; preview: OGAgentLeadImportPreview }>(`/email/extractions/${encodeURIComponent(extractionId)}/request-import-approval`, { method: 'POST' }),
    importApprovedLeads: (extractionId: string) => request<{ approved: number; imported: number; skipped: number; failed: number; records: unknown[]; errors: unknown[] }>(`/email/extractions/${encodeURIComponent(extractionId)}/import-approved`, { method: 'POST' }),
    listBusinessLeads: () => request<OGAgentBusinessLead[]>('/business-leads?limit=100'),
    getBusinessLead: (leadId: string) => request<OGAgentBusinessLead>(`/business-leads/${encodeURIComponent(leadId)}`),
    updateBusinessLeadStatus: (leadId: string, status: string, note = '') => request<OGAgentBusinessLead>(`/business-leads/${encodeURIComponent(leadId)}/status`, { method: 'PATCH', body: JSON.stringify({ status, note }) }),
    listTelecallers: () => request<OGAgentAdminReference[]>('/telecalling/telecallers'),
    getTelecallingConfig: () => request<{ allowTelephoneLinks: boolean; queueLockMinutes: number; minimumCallNoteLength: number; defaultRetryDays: number }>('/telecalling/config'),
    getCallingDashboard: (scope = 'own') => request<OGCallingDashboard>(`/telecalling/dashboard?scope=${scope}`),
    previewCallingCampaign: (input: Record<string, unknown>) => request<Record<string, unknown>>('/telecalling/campaigns/preview', { method: 'POST', body: JSON.stringify(input) }),
    createCallingCampaign: (input: Record<string, unknown>) => request<OGCallingCampaign>('/telecalling/campaigns', { method: 'POST', body: JSON.stringify({ ...input, confirmPreview: true }) }),
    listCallingCampaigns: () => request<OGCallingCampaign[]>('/telecalling/campaigns?limit=100'),
    transitionCallingCampaign: (id: string, action: 'activate' | 'pause' | 'resume' | 'complete' | 'cancel' | 'archive', confirmPending = false) => request<OGCallingCampaign>(`/telecalling/campaigns/${encodeURIComponent(id)}/${action}`, { method: 'POST', body: JSON.stringify({ confirmPending }) }),
    listCallQueue: (scope = 'own') => request<OGCallQueueItem[]>(`/telecalling/queue?scope=${scope}&limit=100`),
    getCallQueueItem: (id: string) => request<OGCallQueueItem>(`/telecalling/queue/${encodeURIComponent(id)}`),
    claimCallQueueItem: (id: string) => request<OGCallQueueItem>(`/telecalling/queue/${encodeURIComponent(id)}/claim`, { method: 'POST' }),
    releaseCallQueueItem: (id: string) => request<OGCallQueueItem>(`/telecalling/queue/${encodeURIComponent(id)}/release`, { method: 'POST' }),
    skipCallQueueItem: (id: string, reason: string) => request<OGCallQueueItem>(`/telecalling/queue/${encodeURIComponent(id)}/skip`, { method: 'POST', body: JSON.stringify({ reason }) }),
    reassignCallQueueItem: (id: string, assignedTo: string) => request<OGCallQueueItem>(`/telecalling/queue/${encodeURIComponent(id)}/reassign`, { method: 'POST', body: JSON.stringify({ assignedTo }) }),
    startManualCall: (id: string) => request<OGCallActivity>(`/telecalling/queue/${encodeURIComponent(id)}/start-manual`, { method: 'POST' }),
    recordCallOutcome: (id: string, input: Record<string, unknown>) => request<{ activity: OGCallActivity; queueItem: OGCallQueueItem; idempotent: boolean }>(`/telecalling/queue/${encodeURIComponent(id)}/outcome`, { method: 'POST', body: JSON.stringify(input) }),
    getLeadCallHistory: (leadId: string) => request<OGCallActivity[]>(`/telecalling/leads/${encodeURIComponent(leadId)}/history?limit=100`),
    generateCallScript: (input: Record<string, unknown>) => request<OGCallScript>('/telecalling/script/generate', { method: 'POST', body: JSON.stringify(input) }),
    listCallScriptTemplates: () => request<OGCallScriptTemplate[]>('/telecalling/script-templates?limit=100'),
    createCallScriptTemplate: (input: Record<string, unknown>) => request<OGCallScriptTemplate>('/telecalling/script-templates', { method: 'POST', body: JSON.stringify(input) }),
    transitionCallScriptTemplate: (id: string, action: 'activate' | 'archive') => request<OGCallScriptTemplate>(`/telecalling/script-templates/${encodeURIComponent(id)}/${action}`, { method: 'POST' }),
    listFollowUps: (scope = 'own') => request<OGFollowUp[]>(`/telecalling/follow-ups?scope=${scope}&limit=100`),
    completeFollowUp: (id: string, completionNote: string, outcome = 'OTHER') => request<OGFollowUp>(`/telecalling/follow-ups/${encodeURIComponent(id)}/complete`, { method: 'POST', body: JSON.stringify({ completionNote, outcome }) }),
    cancelFollowUp: (id: string) => request<OGFollowUp>(`/telecalling/follow-ups/${encodeURIComponent(id)}/cancel`, { method: 'POST' }),
    getCallingSummaryReport: () => request<OGCallingDashboard>('/telecalling/reports/summary'),
    getCallingCampaignReport: (id: string) => request<Record<string, unknown>>(`/telecalling/reports/campaign/${encodeURIComponent(id)}`),
    getCallingTelecallerReport: (id: string) => request<Record<string, unknown>>(`/telecalling/reports/telecaller/${encodeURIComponent(id)}`),
    getCodingConfig: () => request<OGCodingConfig>('/coding/config'),
    createCodingTask: (input: Record<string, unknown>) => request<OGCodingTask>('/coding/tasks', { method: 'POST', body: JSON.stringify(input) }),
    listCodingTasks: () => request<OGCodingTask[]>('/coding/tasks?limit=100'),
    getCodingTask: (id: string) => request<OGCodingTaskDetails>(`/coding/tasks/${encodeURIComponent(id)}`),
    updateCodingTask: (id: string, input: Record<string, unknown>) => request<OGCodingTask>(`/coding/tasks/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify(input) }),
    analyzeCodingTask: (id: string) => request<OGCodingTask>(`/coding/tasks/${encodeURIComponent(id)}/analyze`, { method: 'POST' }),
    cancelCodingTask: (id: string) => request<OGCodingTask>(`/coding/tasks/${encodeURIComponent(id)}/cancel`, { method: 'POST' }),
    getRepositoryStatus: () => request<OGRepositoryStatus>('/coding/repository/status'),
    getRepositoryStructure: (codingTaskId: string, paths: string[] = [], depth = 2) => request<{ entries: { path: string; type: string }[]; truncated: boolean }>('/coding/repository/structure', { method: 'POST', body: JSON.stringify({ codingTaskId, paths, depth }) }),
    searchRepository: (codingTaskId: string, query: string, paths: string[] = []) => request<{ query: string; searchedFiles: number; results: { path: string; matches: { lineNumber: number; snippet: string }[]; relevanceReason: string; contentHash: string }[]; truncated: boolean }>('/coding/repository/search', { method: 'POST', body: JSON.stringify({ codingTaskId, query, paths }) }),
    readRepositoryFile: (codingTaskId: string, path: string, startLine = 1, endLine = 250) => request<{ path: string; startLine: number; endLine: number; totalLines: number; content: string; contentHash: string; truncated: boolean }>('/coding/repository/read', { method: 'POST', body: JSON.stringify({ codingTaskId, path, startLine, endLine }) }),
    requestPatchGeneration: (id: string) => request<OGAgentApproval>(`/coding/tasks/${encodeURIComponent(id)}/request-patch`, { method: 'POST' }),
    generateCodePatch: (id: string, approvalId: string, patchContent: string) => request<OGCodePatch>(`/coding/tasks/${encodeURIComponent(id)}/generate-patch`, { method: 'POST', body: JSON.stringify({ approvalId, patchContent }) }),
    getCodePatch: (id: string) => request<OGCodePatch>(`/coding/patches/${encodeURIComponent(id)}`),
    getCodePatchDiff: (id: string, offset = 0) => request<{ patchId: string; patchHash: string; offset: number; content: string; totalBytes: number; truncated: boolean }>(`/coding/patches/${encodeURIComponent(id)}/diff?offset=${offset}&limit=50000`),
    requestPatchApplyApproval: (id: string) => request<{ approval: OGAgentApproval; highRiskApproval?: OGAgentApproval | null }>(`/coding/patches/${encodeURIComponent(id)}/request-apply-approval`, { method: 'POST' }),
    applyCodePatch: (id: string) => request<{ patchId: string; filesChanged: string[]; gitStatus: string }>(`/coding/patches/${encodeURIComponent(id)}/apply`, { method: 'POST' }),
    requestPatchRevertApproval: (id: string) => request<OGAgentApproval>(`/coding/patches/${encodeURIComponent(id)}/request-revert-approval`, { method: 'POST' }),
    revertCodePatch: (id: string) => request<{ patchId: string; filesReverted: string[] }>(`/coding/patches/${encodeURIComponent(id)}/revert`, { method: 'POST' }),
    listCodeCommands: () => request<OGCodeCommand[]>('/coding/commands'),
    previewCodeCommand: (codingTaskId: string, commandId: string, patchId?: string) => request<{ command: OGCodeCommand; approvalRequired: boolean; approval?: OGAgentApproval | null }>(`/coding/tasks/${encodeURIComponent(codingTaskId)}/commands/preview`, { method: 'POST', body: JSON.stringify({ commandId, patchId }) }),
    runCodeCommand: (codingTaskId: string, commandId: string, approvalId?: string, patchId?: string, idempotencyKey?: string) => request<OGCodeCommandRun>(`/coding/tasks/${encodeURIComponent(codingTaskId)}/commands/run`, { method: 'POST', body: JSON.stringify({ commandId, approvalId, patchId, idempotencyKey }) }),
    getCodeCommandRun: (id: string) => request<OGCodeCommandRun>(`/coding/command-runs/${encodeURIComponent(id)}`),
    cancelCodeCommandRun: (id: string) => request<OGCodeCommandRun>(`/coding/command-runs/${encodeURIComponent(id)}/cancel`, { method: 'POST' }),
  };
};

export type OGAgentApi = ReturnType<typeof createOGAgentApi>;
