export const BUSINESS_MAIL_ERROR_CODES = Object.freeze({
  INVALID_REQUEST: "BUSINESS_MAIL_INVALID_REQUEST",
  INVALID_RECIPIENT: "BUSINESS_MAIL_INVALID_RECIPIENT",
  INVALID_SUBJECT: "BUSINESS_MAIL_INVALID_SUBJECT",
  INVALID_CONTENT: "BUSINESS_MAIL_INVALID_CONTENT",
  UNKNOWN_SENDER_PROFILE: "BUSINESS_MAIL_UNKNOWN_SENDER_PROFILE",
  SENDER_DISABLED: "BUSINESS_MAIL_SENDER_DISABLED",
  SENDER_ACCESS_DENIED: "BUSINESS_MAIL_SENDER_ACCESS_DENIED",
  PROVIDER_NOT_CONFIGURED: "BUSINESS_MAIL_PROVIDER_NOT_CONFIGURED",
  PROVIDER_UNSUPPORTED: "BUSINESS_MAIL_PROVIDER_UNSUPPORTED",
  PROVIDER_TIMEOUT: "BUSINESS_MAIL_PROVIDER_TIMEOUT",
  PROVIDER_REJECTED: "BUSINESS_MAIL_PROVIDER_REJECTED",
  SEND_FAILED: "BUSINESS_MAIL_SEND_FAILED",
  UNSUPPORTED_CC: "BUSINESS_MAIL_UNSUPPORTED_CC",
  UNSUPPORTED_BCC: "BUSINESS_MAIL_UNSUPPORTED_BCC",
  UNSUPPORTED_ATTACHMENTS: "BUSINESS_MAIL_UNSUPPORTED_ATTACHMENTS",
  UNSAFE_HTML: "BUSINESS_MAIL_UNSAFE_HTML",
  IDEMPOTENCY_CONFLICT: "BUSINESS_MAIL_IDEMPOTENCY_CONFLICT",
});

const DEFAULT_STATUS_BY_CODE = Object.freeze({
  [BUSINESS_MAIL_ERROR_CODES.INVALID_REQUEST]: 400,
  [BUSINESS_MAIL_ERROR_CODES.INVALID_RECIPIENT]: 400,
  [BUSINESS_MAIL_ERROR_CODES.INVALID_SUBJECT]: 400,
  [BUSINESS_MAIL_ERROR_CODES.INVALID_CONTENT]: 400,
  [BUSINESS_MAIL_ERROR_CODES.UNKNOWN_SENDER_PROFILE]: 400,
  [BUSINESS_MAIL_ERROR_CODES.SENDER_DISABLED]: 403,
  [BUSINESS_MAIL_ERROR_CODES.SENDER_ACCESS_DENIED]: 403,
  [BUSINESS_MAIL_ERROR_CODES.PROVIDER_NOT_CONFIGURED]: 503,
  [BUSINESS_MAIL_ERROR_CODES.PROVIDER_UNSUPPORTED]: 503,
  [BUSINESS_MAIL_ERROR_CODES.PROVIDER_TIMEOUT]: 504,
  [BUSINESS_MAIL_ERROR_CODES.PROVIDER_REJECTED]: 502,
  [BUSINESS_MAIL_ERROR_CODES.SEND_FAILED]: 502,
  [BUSINESS_MAIL_ERROR_CODES.UNSUPPORTED_CC]: 400,
  [BUSINESS_MAIL_ERROR_CODES.UNSUPPORTED_BCC]: 400,
  [BUSINESS_MAIL_ERROR_CODES.UNSUPPORTED_ATTACHMENTS]: 400,
  [BUSINESS_MAIL_ERROR_CODES.UNSAFE_HTML]: 400,
  [BUSINESS_MAIL_ERROR_CODES.IDEMPOTENCY_CONFLICT]: 409,
});

export class BusinessMailError extends Error {
  constructor(code, message, options = {}) {
    super(message);
    this.name = "BusinessMailError";
    this.code = code;
    this.statusCode = options.statusCode || DEFAULT_STATUS_BY_CODE[code] || 500;
    if (options.cause) {
      Object.defineProperty(this, "cause", {
        value: options.cause,
        enumerable: false,
        configurable: true,
      });
    }
  }
}

export const isBusinessMailError = (error) => error instanceof BusinessMailError;
